apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sveltos-dashboard.backendManagerLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sveltos-dashboard.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend-manager
  template:
    metadata:
      labels:
        {{- include "sveltos-dashboard.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend-manager
    spec:
      serviceAccountName: {{ .Values.backendManager.serviceAccountName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.backendManager.podSecurityContext | nindent 8 }}
      containers:
      - name: backend-manager
        args:
          - --diagnostics-address=:8443
          - --v=5
        command:
          - /manager
        securityContext: {{- toYaml .Values.backendManager.securityContext | nindent 10 }}
        image: "{{ .Values.backendManager.image.repository }}:{{ .Values.backendManager.image.tag | default "main" }}"
        imagePullPolicy: {{ .Values.backendManager.image.pullPolicy }}
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.backendManager.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.backendManager.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.backendManager.resources | nindent 10 }}
      {{- with .Values.backendManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
