apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "sveltos-dashboard.backendManagerLabels" . | nindent 4 }}
  name: backend-controller-role
rules:
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - authentication.k8s.io
  resources:
    - tokenreviews
  verbs:
    - create
- apiGroups:
    - authorization.k8s.io
  resources:
    - subjectaccessreviews
  verbs:
    - create
- apiGroups:
    - cluster.x-k8s.io
  resources:
    - clusters
    - clusters/status
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - config.projectsveltos.io
  resources:
    - clusterconfigurations
    - clusterprofiles
    - clusterprofiles/status
    - clustersummaries
    - clustersummaries/status
    - profiles
    - profiles/status
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - lib.projectsveltos.io
  resources:
    - debuggingconfigurations
    - sveltosclusters
    - sveltosclusters/status
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "sveltos-dashboard.backendManagerLabels" . | nindent 4 }}
  name: backendManager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backend-controller-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backendManager.serviceAccountName }}
    namespace: {{ .Release.Namespace }}